In [ ]:
# Numpy: provides high performance multidimentional array objects

In [1]:
import numpy as np
lst = [1,2,3,4,5]
arr = np.array(lst)
print(type(arr))

<class 'numpy.ndarray'>


In [2]:
print(arr)

[1 2 3 4 5]


In [3]:
arr.shape

(5,)

In [4]:
lst1 = [1,2,3,4]
lst2 = [2,3,4,5]
lst3 = [4,5,6,7]

arr = np.array([lst1,lst2,lst3])
print(arr)

[[1 2 3 4]
 [2 3 4 5]
 [4 5 6 7]]


In [5]:
arr

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [7]:
arr.shape

(3, 4)

In [9]:
arr.reshape(4,3)  #total number of elements will remains same.

array([[1, 2, 3],
       [4, 2, 3],
       [4, 5, 4],
       [5, 6, 7]])

In [10]:
arr.reshape(2,6)

array([[1, 2, 3, 4, 2, 3],
       [4, 5, 4, 5, 6, 7]])

In [12]:
arr[2]

array([4, 5, 6, 7])

In [13]:
arr

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [14]:
arr[1:3]

array([[2, 3, 4, 5],
       [4, 5, 6, 7]])

In [15]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [16]:
arr[1:,3:]

array([[5],
       [7]])

In [20]:
arr = np.arange(0,20,step=2)

In [21]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [25]:
#copy fun and broadcasting
arr[3:]=100
arr

array([  0,   2,   4, 100, 100, 100, 100, 100, 100, 100])

In [30]:
#some conditions very useful in exploratory data analysis
val =2
arr*2

array([  0,   4,   8, 200, 200, 200, 200, 200, 200, 200])

In [33]:
arr[arr<100]

array([0, 2, 4])

In [34]:
np.ones(4)

array([1., 1., 1., 1.])

In [36]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [38]:
#random distribution
np.random.rand(3,3)

array([[0.25428391, 0.04639791, 0.12783112],
       [0.245613  , 0.04169782, 0.84385593],
       [0.1378558 , 0.73759265, 0.01803933]])

In [39]:
np.random.randint(0,100,8)

array([70, 24, 86, 11, 39, 72, 50, 99])

In [41]:
np.random.randint(0,100,8).reshape(2,4)

array([[70, 29, 97, 59],
       [56, 12, 30,  7]])